# CPSC 375 Classwork - Data wrangling - Pandas

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ProfAvery/cpsc375-classwork/blob/main/wrangling-pandas.ipynb)

- *Manager*:
- *Recorder*:
- *Presenter*:
- *Timekeeper*:

*Note*: On Google Colab, run the following code cell to download the `cpsc375` module before trying to `import`:

In [46]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [47]:
from cpsc375 import *

## Part 1 - Slide 18

From the iris dataset, show only Sepal.Length and Sepal.Width columns for those flowers with Petal.Length > 3.0 and Petal.Width > 1.0

In [48]:
(
    iris
    .query('`Petal.Length` > 3.0 and `Petal.Width` > 1.0')
    .filter(['Sepal.Length','Sepal.Width'])
)

     Sepal.Length  Sepal.Width
50            7.0          3.2
51            6.4          3.2
52            6.9          3.1
53            5.5          2.3
54            6.5          2.8
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[92 rows x 2 columns]

In [49]:
add = (lambda a, b: a + b)

add(2, 3)

5

## Part 2 - Slide 21

In [50]:
?mpg_dataset

Show only manufacturer and cty columns in increasing order of cty

In [51]:
(
  mpg
  .sort_values("cty")
  .filter(['manufacturer', 'cty'])
)

    manufacturer  cty
54         dodge    9
59         dodge    9
69         dodge    9
65         dodge    9
126         jeep    9
..           ...  ...
99         honda   28
196       toyota   28
222   volkswagen   29
212   volkswagen   33
221   volkswagen   35

[234 rows x 2 columns]

 Show only manufacturer, cty, hwy columns in increasing order of cty

In [52]:
(
    mpg
    .sort_values("cty")
    .filter(['manufacturer', 'cty', 'hwy'])
)

    manufacturer  cty  hwy
54         dodge    9   12
59         dodge    9   12
69         dodge    9   12
65         dodge    9   12
126         jeep    9   12
..           ...  ...  ...
99         honda   28   33
196       toyota   28   37
222   volkswagen   29   41
212   volkswagen   33   44
221   volkswagen   35   44

[234 rows x 3 columns]

Show only manufacturer, cty, hwy columns ordered first by cty, then by hwy

In [53]:
(
    mpg
    .sort_values(by=['cty','hwy'])
    .filter(['manufacturer', 'cty', 'hwy'])
)

    manufacturer  cty  hwy
54         dodge    9   12
59         dodge    9   12
65         dodge    9   12
69         dodge    9   12
126         jeep    9   12
..           ...  ...  ...
99         honda   28   33
196       toyota   28   37
222   volkswagen   29   41
212   volkswagen   33   44
221   volkswagen   35   44

[234 rows x 3 columns]

Show only manufacturer, cty, hwy columns in decreasing order of cty

In [54]:
(
    mpg
    .sort_values('cty', ascending=False)
    .filter(['manufacturer', 'cty', 'hwy'])
)

    manufacturer  cty  hwy
221   volkswagen   35   44
212   volkswagen   33   44
222   volkswagen   29   41
196       toyota   28   37
99         honda   28   33
..           ...  ...  ...
69         dodge    9   12
54         dodge    9   12
59         dodge    9   12
65         dodge    9   12
126         jeep    9   12

[234 rows x 3 columns]

Show only manufacturer, cty, hwy columns for cars made by audi in decreasing order of cty

In [55]:
(
    mpg
    .sort_values('cty', ascending=False)
    .query('manufacturer == "audi"')
    .filter(['manufacturer', 'cty', 'hwy'])
)

   manufacturer  cty  hwy
3          audi   21   30
1          audi   21   29
2          audi   20   31
9          audi   20   28
10         audi   19   27
7          audi   18   26
0          audi   18   29
6          audi   18   27
5          audi   18   26
13         audi   17   25
12         audi   17   25
16         audi   17   25
17         audi   16   23
4          audi   16   26
8          audi   16   25
11         audi   15   25
14         audi   15   25
15         audi   15   24

Show only manufacturer, cty, hwy columns for cars made by honda in decreasing order of cty and cty > 25

In [56]:
(
    mpg
    .sort_values(['cty'], ascending=False)
    .filter(['manufacturer', 'cty', 'hwy'])
    .query("manufacturer == 'honda' and cty > 25")
)

    manufacturer  cty  hwy
99         honda   28   33
104        honda   26   34

Show only models of cars made by honda in decreasing order of cty and cty > 25

In [57]:
(
    mpg
    .sort_values('cty', ascending=False)
    .query("manufacturer == 'honda' and cty > 25")
    .filter(['model'])
)

     model
99   civic
104  civic

## Part 3 - Slide 28

The `flights` table in the *nycflights13* dataset contains flight arrival and departure data. Apply Pandas data wrangling methods to answer these questions. For each question, **give only the (one line) code**.

In [58]:
?nycflights13_dataset

1. List data only for flights that departed on February 12, 2013.

In [59]:
(
    flights
    .query("year == 2013 and month == 2 and day == 12")
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
120751,2013,2,12,17.0,2245,92.0,122.0,2356,86.0,B6,128,N627JB,JFK,BTV,47.0,266,22,45,2013-02-13T03:00:00Z
120752,2013,2,12,506.0,500,6.0,703.0,648,15.0,US,1117,N193UW,EWR,CLT,90.0,529,5,0,2013-02-12T10:00:00Z
120753,2013,2,12,520.0,525,-5.0,837.0,820,17.0,UA,1018,N37277,EWR,IAH,239.0,1400,5,25,2013-02-12T10:00:00Z
120754,2013,2,12,524.0,530,-6.0,922.0,831,51.0,UA,1219,N77530,LGA,IAH,270.0,1416,5,30,2013-02-12T10:00:00Z
120755,2013,2,12,535.0,540,-5.0,950.0,1016,-26.0,B6,725,N659JB,JFK,BQN,175.0,1576,5,40,2013-02-12T10:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121639,2013,2,12,NaN,1805,NaN,NaN,1955,NaN,MQ,4626,N501MQ,LGA,CMH,NaN,479,18,5,2013-02-12T23:00:00Z
121640,2013,2,12,NaN,700,NaN,NaN,839,NaN,UA,287,NaN,LGA,ORD,NaN,733,7,0,2013-02-12T12:00:00Z
121641,2013,2,12,NaN,625,NaN,NaN,934,NaN,UA,1602,NaN,LGA,IAH,NaN,1416,6,25,2013-02-12T11:00:00Z
121642,2013,2,12,NaN,615,NaN,NaN,820,NaN,US,1791,NaN,JFK,CLT,NaN,541,6,15,2013-02-12T11:00:00Z
121643,2013,2,12,NaN,1300,NaN,NaN,1406,NaN,US,2128,NaN,LGA,BOS,NaN,184,13,0,2013-02-12T18:00:00Z

2. List data only for flights that were delayed (both arrival and departure) by more than 2 hours.

In [60]:
(
  flights
  .query("dep_delay > 120 and arr_delay > 120")
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
649,2013,1,1,1815.0,1325,290.0,2120.0,1542,338.0,EV,4417,N17185,EWR,OMA,213.0,1134,13,25,2013-01-01T18:00:00Z
673,2013,1,1,1842.0,1422,260.0,1958.0,1535,263.0,EV,4633,N18120,EWR,BTV,46.0,266,14,22,2013-01-01T19:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

3. List data only for flights that were delayed (either arrival or departure) by more than 2 hours.

In [61]:
(
    flights
    .query("dep_delay > 120 or arr_delay > 120")
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

4. List data only for flights that were operated by United, American, or Delta.

In [68]:
(
    flights
    .query("carrier in ['UA','AA','DL']")
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T10:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-10-01T01:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z

In [67]:
flights['carrier'].unique()

array(['UA', 'AA', 'B6', 'DL', 'EV', 'MQ', 'US', 'WN', 'VX', 'FL', 'AS',
       '9E', 'F9', 'HA', 'YV', 'OO'], dtype=object)

5. Sort data in order of fastest flights (air_time).

In [72]:
(
    flights
    .sort_values('air_time')
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
176604,2013,4,13,537.0,527,10.0,622.0,628,-6.0,EV,4631,N12167,EWR,BDL,20.0,116,5,27,2013-04-13T09:00:00Z
13524,2013,1,16,1355.0,1315,40.0,1442.0,1411,31.0,EV,4368,N16911,EWR,BDL,20.0,116,13,15,2013-01-16T18:00:00Z
88289,2013,12,6,922.0,851,31.0,1021.0,954,27.0,EV,4276,N27200,EWR,BDL,21.0,116,8,51,2013-12-06T13:00:00Z
115062,2013,2,5,1303.0,1315,-12.0,1342.0,1411,-29.0,EV,4368,N13955,EWR,BDL,21.0,116,13,15,2013-02-05T18:00:00Z
143445,2013,3,8,2026.0,1935,51.0,2131.0,2056,35.0,9E,3650,N8501F,JFK,PHL,21.0,94,19,35,2013-03-09T00:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

6. Sort data in order of longest duration flights (air_time).

In [73]:
(
    flights
    .sort_values('air_time', ascending=False)
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
151467,2013,3,17,1337.0,1335,2.0,1937.0,1836,61.0,UA,15,N77066,EWR,HNL,695.0,4963,13,35,2013-03-17T17:00:00Z
115752,2013,2,6,853.0,900,-7.0,1542.0,1540,2.0,HA,51,N389HA,JFK,HNL,691.0,4983,9,0,2013-02-06T14:00:00Z
151311,2013,3,17,1006.0,1000,6.0,1607.0,1530,37.0,HA,51,N380HA,JFK,HNL,686.0,4983,10,0,2013-03-17T14:00:00Z
149618,2013,3,15,1001.0,1000,1.0,1551.0,1530,21.0,HA,51,N388HA,JFK,HNL,686.0,4983,10,0,2013-03-15T14:00:00Z
150547,2013,3,16,1001.0,1000,1.0,1544.0,1530,14.0,HA,51,N384HA,JFK,HNL,683.0,4983,10,0,2013-03-16T14:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

7. Show only the origin and destination of flights sorted by longest duration flights.

In [75]:
(
    flights
    .sort_values('air_time', ascending=False)
    .filter(['origin', 'dest'])
)

       origin dest
151467    EWR  HNL
115752    JFK  HNL
151311    JFK  HNL
149618    JFK  HNL
150547    JFK  HNL
...       ...  ...
336771    JFK  DCA
336772    LGA  SYR
336773    LGA  BNA
336774    LGA  CLE
336775    LGA  RDU

[336776 rows x 2 columns]

8. Add a new variable that indicates the total delay (both departure and arrival delay).

In [76]:
flights['total_delay'] = flights['dep_delay'] + flights['arr_delay']

In [77]:
flights

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,total_delay
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,13.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,24.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,35.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,-19.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,-31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

9. Show only the origin and destination of flights sorted by descending order of total delay.

In [80]:
(
    flights
    .sort_values("total_delay", ascending=False)
    .filter(['origin', 'dest'])
)

       origin dest
7072      JFK  HNL
235778    JFK  CMH
8239      EWR  ORD
327043    JFK  SFO
270376    JFK  CVG
...       ...  ...
336771    JFK  DCA
336772    LGA  SYR
336773    LGA  BNA
336774    LGA  CLE
336775    LGA  RDU

[336776 rows x 2 columns]

10. Show only the origin and destination of 10 most delayed flights

    *Hint*: there are multiple ways of solving this. Some additional methods that you will find useful are `.iloc`, `head()`, `nlargest()`, `rank(method='min')`.

In [82]:
(
    flights
    .sort_values("total_delay", ascending=False)
    .filter(['origin', 'dest'])
    .iloc[:10]
)

       origin dest
7072      JFK  HNL
235778    JFK  CMH
8239      EWR  ORD
327043    JFK  SFO
270376    JFK  CVG
173992    JFK  TPA
151974    LGA  MSP
270987    LGA  ATL
87238     EWR  MIA
195711    EWR  ORD

11. Show the average total delay for every departure city.

In [88]:
(
    flights
    .groupby('origin')['total_delay']
    .mean()
)

origin
EWR    24.116165
JFK    17.575088
LGA    16.070071
Name: total_delay, dtype: float64

In [87]:
flights['origin']

0         EWR
1         LGA
2         JFK
3         JFK
4         LGA
         ...
336771    JFK
336772    LGA
336773    LGA
336774    LGA
336775    LGA
Name: origin, Length: 336776, dtype: object

12. Show the average total delay for every departure-arrival city pair.

In [90]:
(
    flights
    .groupby(['origin', 'dest'])['total_delay']
    .mean()
)

origin  dest
EWR     ALB     37.844498
        ANC     10.375000
        ATL     28.626743
        AUS     11.000000
        AVL     17.382470
                  ...
LGA     SYR     28.401487
        TPA     19.394167
        TVC     39.383562
        TYS     16.600000
        XNA     12.122708
Name: total_delay, Length: 224, dtype: float64

## Part 4 - Slide 32

Show the three most efficient car manufacturers (mean city mileage of all their cars) from the mpg dataset

In [97]:
(
    mpg
    .groupby('manufacturer')['cty']
    .mean()
    .sort_values(ascending=False)
    .iloc[:3]
)

manufacturer
honda         24.444444
volkswagen    20.925926
subaru        19.285714
Name: cty, dtype: float64