# CPSC 375 Classwork - Data wrangling - Joins and Tidy Data

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ProfAvery/cpsc375-classwork/blob/main/wrangling-tidy.ipynb)

- *Manager*:
- *Recorder*:
- *Presenter*:
- *Timekeeper*:

*Note*: On Google Colab, run the following code cell to download the `cpsc375` module before trying to `import`:

In [25]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [26]:
from cpsc375 import *

## Part 1 - Slide 10

In [27]:
band_members = pd.DataFrame(
    {"Name": ["Mick", "John", "Paul"], "Band": ["Stones", "Beatles", "Beatles"]}
)

band_instruments = pd.DataFrame(
    {"Name": ["John", "Paul", "Keith"], "Plays": ["guitar", "bass", "guitar"]}
)

<table>
<tr>
  <th>
    <code>band_members_4rows</code> (left table)
  </th>
  <th>
    <code>band_instruments_4rows</code> (right table)
  </th>
</tr>
<tr>
  <td>

| Name | Band    |
|------|---------|
| Mick | Stones  |
| John | Beatles |
| Paul | Beatles |
| Paul | Wings   |

  </td>
  <td>

| Name  | Plays  |
|-------|--------|
| John  | guitar |
| Paul  | bass   |
| Keith | guitar |
| Paul  | vocals |

  </td>
</tr>
</table>

Calculate the different joins for these two tables.

First, do them by hand

Then, confirm your results with code

In [28]:
band_members_4rows = pd.concat([
  band_members,
  pd.DataFrame(dict(Name=["Paul"], Band=["Wings"]))
], ignore_index=True)

band_instruments_4rows = pd.concat([
    band_instruments,
    pd.DataFrame(dict(Name=["Paul"], Plays=["vocals"]))
], ignore_index=True)

inner_join_band = band_members_4rows.merge(band_instruments_4rows)
left_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="left")
right_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="right")
outer_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="outer")

inner_join_band, left_join_band, right_join_band, outer_join_band

(   Name     Band   Plays
 0  John  Beatles  guitar
 1  Paul  Beatles    bass
 2  Paul  Beatles  vocals
 3  Paul    Wings    bass
 4  Paul    Wings  vocals,
    Name     Band   Plays
 0  Mick   Stones     NaN
 1  John  Beatles  guitar
 2  Paul  Beatles    bass
 3  Paul  Beatles  vocals
 4  Paul    Wings    bass
 5  Paul    Wings  vocals,
     Name     Band   Plays
 0   John  Beatles  guitar
 1   Paul  Beatles    bass
 2   Paul    Wings    bass
 3  Keith      NaN  guitar
 4   Paul  Beatles  vocals
 5   Paul    Wings  vocals,
     Name     Band   Plays
 0   John  Beatles  guitar
 1  Keith      NaN  guitar
 2   Mick   Stones     NaN
 3   Paul  Beatles    bass
 4   Paul  Beatles  vocals
 5   Paul    Wings    bass
 6   Paul    Wings  vocals)

## Part 2 - Slide 28

Write code to "tidy" this dataset

In [29]:
grades = pd.DataFrame(
  dict(
    CWID=(1234567, 2356902, 5005667),
    NAME=("Mary", "Lee", "Elena"),
    CPSC120=(3, 4, pd.NA),
    CPSC121=(3.3, 3, 2),
    CPSC131=(3, 4, 3.7),
    MATH338=(3, pd.NA, 3.3),
  )
)

In [30]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades")
grades_tidy

       CWID   NAME  Courses Grades
0   1234567   Mary  CPSC120      3
1   2356902    Lee  CPSC120      4
2   5005667  Elena  CPSC120   <NA>
3   1234567   Mary  CPSC121    3.3
4   2356902    Lee  CPSC121    3.0
5   5005667  Elena  CPSC121    2.0
6   1234567   Mary  CPSC131    3.0
7   2356902    Lee  CPSC131    4.0
8   5005667  Elena  CPSC131    3.7
9   1234567   Mary  MATH338      3
10  2356902    Lee  MATH338   <NA>
11  5005667  Elena  MATH338    3.3

In [31]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades").dropna(subset=["Grades"])
grades_tidy

       CWID   NAME  Courses Grades
0   1234567   Mary  CPSC120      3
1   2356902    Lee  CPSC120      4
3   1234567   Mary  CPSC121    3.3
4   2356902    Lee  CPSC121    3.0
5   5005667  Elena  CPSC121    2.0
6   1234567   Mary  CPSC131    3.0
7   2356902    Lee  CPSC131    4.0
8   5005667  Elena  CPSC131    3.7
9   1234567   Mary  MATH338      3
11  5005667  Elena  MATH338    3.3

In [32]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades").dropna(subset=["Grades"]).reset_index(drop=True)
grades_tidy

      CWID   NAME  Courses Grades
0  1234567   Mary  CPSC120      3
1  2356902    Lee  CPSC120      4
2  1234567   Mary  CPSC121    3.3
3  2356902    Lee  CPSC121    3.0
4  5005667  Elena  CPSC121    2.0
5  1234567   Mary  CPSC131    3.0
6  2356902    Lee  CPSC131    4.0
7  5005667  Elena  CPSC131    3.7
8  1234567   Mary  MATH338      3
9  5005667  Elena  MATH338    3.3

## Part 3 - Slide 33

`language_diversity.csv` contains data on the diversity of languages in different countries and other parameters.

In [33]:
language_diversity = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/language_diversity.csv"
)

In [34]:
language_diversity.head(12)

   Continent       Country Measurement  Value
0     Africa       Algeria       Langs   18.0
1     Africa        Angola       Langs   42.0
2    Oceania     Australia       Langs  234.0
3       Asia    Bangladesh       Langs   37.0
4     Africa         Benin       Langs   52.0
5   Americas       Bolivia       Langs   38.0
6     Africa      Botswana       Langs   27.0
7   Americas        Brazil       Langs  209.0
8     Africa  Burkina Faso       Langs   75.0
9     Africa           CAR       Langs   94.0
10      Asia      Cambodia       Langs   18.0
11    Africa      Cameroon       Langs  275.0

In [35]:
language_diversity[language_diversity["Country"] == "Algeria"]

    Continent  Country Measurement       Value
0      Africa  Algeria       Langs       18.00
74     Africa  Algeria        Area  2381741.00
148    Africa  Algeria  Population    25660.00
222    Africa  Algeria    Stations      102.00
296    Africa  Algeria         MGS        6.60
370    Africa  Algeria         Std        2.29

In [36]:
language_diversity_pivot = language_diversity.pivot(index=["Continent", "Country"], columns="Measurement", values="Value")
language_diversity_pivot

Measurement                      Area  Langs    MGS  Population  Stations  \
Continent Country
Africa    Algeria           2381741.0   18.0   6.60     25660.0     102.0
          Angola            1246700.0   42.0   6.22     10303.0      50.0
          Benin              112622.0   52.0   7.14      4889.0       7.0
          Botswana           581730.0   27.0   4.60      1348.0      10.0
          Burkina Faso       274000.0   75.0   5.17      9242.0       6.0
...                               ...    ...    ...         ...       ...
Asia      Yemen              527968.0    6.0   0.00     12302.0       2.0
Oceania   Australia         7713364.0  234.0   6.00     17336.0     134.0
          Papua New Guinea   462840.0  862.0  10.88      3772.0       8.0
          Solomon Islands     28896.0   66.0  12.00      3301.0       1.0
          Vanuatu             12189.0  111.0  12.00       163.0       4.0

Measurement                  Std
Continent Country
Africa    Algeria           2.29
          Angola            1.87
          Benin             0.99
          Botswana          1.69
          Burkina Faso      1.07
...                          ...
Asia      Yemen             0.00
Oceania   Australia         4.17
          Papua New Guinea  1.96
          Solomon Islands   0.00
          Vanuatu           0.00

[74 rows x 6 columns]

In [37]:
language_diversity_pivot = language_diversity.pivot(index=["Continent", "Country"], columns="Measurement", values="Value").reset_index().rename_axis(None, axis=1)
language_diversity_pivot

,Continent,Country,Area,Langs,MGS,Population,Stations,Std
0,Africa,Algeria,2381741.0,18.0,6.60,25660.0,102.0,2.29
1,Africa,Angola,1246700.0,42.0,6.22,10303.0,50.0,1.87
2,Africa,Benin,112622.0,52.0,7.14,4889.0,7.0,0.99
3,Africa,Botswana,581730.0,27.0,4.60,1348.0,10.0,1.69
4,Africa,Burkina Faso,274000.0,75.0,5.17,9242.0,6.0,1.07
...,...,...,...,...,...,...,...,...
69,Asia,Yemen,527968.0,6.0,0.00,12302.0,2.0,0.00
70,Oceania,Australia,7713364.0,234.0,6.00,17336.0,134.0,4.17
71,Oceania,Papua New Guinea,462840.0,862.0,10.88,3772.0,8.0,1.96
72,Oceania,Solomon Islands,28896.0,66.0,12.00,3301.0,1.0,0.00
73,Oceania,Vanuatu,12189.0,111.0,12.00,163.0,4.0,0.00

Calculate:
 * The total number of languages in every continent

In [38]:
langs_continent = language_diversity_pivot.groupby("Continent")["Langs"].sum()
langs_continent

Continent
Africa      2513.0
Americas     877.0
Asia        1977.0
Oceania     1273.0
Name: Langs, dtype: float64

* Add a new variable that shows for every country its population density
  (PopulationDensity=Population/Area)

Hint: **First** convert to tidy data using `pivot()`

In [39]:
language_diversity_pivot["PopulationDensity"] = (language_diversity_pivot["Population"]/language_diversity_pivot["Area"])
language_diversity_pivot

,Continent,Country,Area,Langs,MGS,Population,Stations,Std,PopulationDensity
0,Africa,Algeria,2381741.0,18.0,6.60,25660.0,102.0,2.29,0.010774
1,Africa,Angola,1246700.0,42.0,6.22,10303.0,50.0,1.87,0.008264
2,Africa,Benin,112622.0,52.0,7.14,4889.0,7.0,0.99,0.043411
3,Africa,Botswana,581730.0,27.0,4.60,1348.0,10.0,1.69,0.002317
4,Africa,Burkina Faso,274000.0,75.0,5.17,9242.0,6.0,1.07,0.033730
...,...,...,...,...,...,...,...,...,...
69,Asia,Yemen,527968.0,6.0,0.00,12302.0,2.0,0.00,0.023301
70,Oceania,Australia,7713364.0,234.0,6.00,17336.0,134.0,4.17,0.002248
71,Oceania,Papua New Guinea,462840.0,862.0,10.88,3772.0,8.0,1.96,0.008150
72,Oceania,Solomon Islands,28896.0,66.0,12.00,3301.0,1.0,0.00,0.114237
73,Oceania,Vanuatu,12189.0,111.0,12.00,163.0,4.0,0.00,0.013373

Original dataset:
 * <https://github.com/jvcasillas/untidydata#language_diversity>
 * <https://www.researchgate.net/publication/222464328_Explaining_Global_Patterns_of_Language_Diversity>

## Part 4 - Slide 36

`horse_racing.csv` contains data related to horse racing licensing in New York.

In [40]:
horse_racing = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/horse_racing.csv"
)

Transform the dataset such that:

* The License column is split into two:
  - `LicenseOrReceipt`: a categorical variable with two categories "License" and "Receipt"
  - `Number`: numeric column with the license/receipt number

In [41]:
horse_racing["License"].head()

0    LICENSE # 1522818
1    RECEIPT # 1462171
2    RECEIPT # 1462094
3    RECEIPT # 1449814
4    LICENSE # 1522183
Name: License, dtype: object

In [42]:
horse_racing[["LicenseOrReceipt","Number"]] = horse_racing.License.str.split(' # ', expand=True)
horse_racing[["LicenseOrReceipt", "Number"]]

      LicenseOrReceipt   Number
0              LICENSE  1522818
1              RECEIPT  1462171
2              RECEIPT  1462094
3              RECEIPT  1449814
4              LICENSE  1522183
...                ...      ...
24186          RECEIPT  1461411
24187          RECEIPT  1461729
24188          RECEIPT  1456356
24189          RECEIPT  1464481
24190          RECEIPT  1459607

[24191 rows x 2 columns]

In [43]:
horse_racing["Number"].dtype

dtype('O')

In [44]:
horse_racing["Number"] = horse_racing["Number"].astype(int)

In [45]:
horse_racing["Number"].dtype

dtype('int64')

In [46]:
horse_racing["LicenseOrReceipt"] = horse_racing.LicenseOrReceipt.str.capitalize()

In [47]:
horse_racing["LicenseOrReceipt"].unique()

array(['License', 'Receipt'], dtype=object)

In [48]:
horse_racing["License"]

0        LICENSE # 1522818
1        RECEIPT # 1462171
2        RECEIPT # 1462094
3        RECEIPT # 1449814
4        LICENSE # 1522183
               ...
24186    RECEIPT # 1461411
24187    RECEIPT # 1461729
24188    RECEIPT # 1456356
24189    RECEIPT # 1464481
24190    RECEIPT # 1459607
Name: License, Length: 24191, dtype: object

In [49]:
horse_racing = horse_racing.drop('License', axis=1)

* The `Expires` column is split into three:
  - `Year`, `Month`, `Day` (all integers)

In [50]:
horse_racing["Expires"]

0          4/2/2021
1        11/18/2019
2         12/7/2019
3        12/31/2020
4         5/11/2021
            ...
24186     9/25/2019
24187    11/26/2019
24188      7/6/2019
24189    12/31/2019
24190     1/15/2020
Name: Expires, Length: 24191, dtype: object

In [51]:
horse_racing[["Month", "Day", "Year"]] = horse_racing.Expires.str.split("/", expand=True)
horse_racing[["Month", "Day", "Year"]]

      Month Day  Year
0         4   2  2021
1        11  18  2019
2        12   7  2019
3        12  31  2020
4         5  11  2021
...     ...  ..   ...
24186     9  25  2019
24187    11  26  2019
24188     7   6  2019
24189    12  31  2019
24190     1  15  2020

[24191 rows x 3 columns]

In [52]:
horse_racing[["Month", "Day", "Year"]] = horse_racing[["Month", "Day", "Year"]].astype(int)

In [53]:
horse_racing["Month"].dtype

dtype('int64')

In [54]:
horse_racing = horse_racing.drop("Expires", axis=1)

In [55]:
horse_racing.head()

,PersonID,Name,Occupation,Eligibility,Division,LicenseOrReceipt,Number,Month,Day,Year
0,120384,0MAR MEHIDI,EXERCISE RIDER,ABLE TO PARTICIPATE,THOROUGHBRED,License,1522818,4,2,2021
1,148737,AADIL S. KHAN,EXERCISE RIDER,ABLE TO PARTICIPATE,THOROUGHBRED,Receipt,1462171,11,18,2019
2,200788,AALIYAH R. MCKUNE,SECURITY,ABLE TO PARTICIPATE,HARNESS,Receipt,1462094,12,7,2019
3,200514,AAMER A. SALMAN,OWNER ORIGINAL,ABLE TO PARTICIPATE,THOROUGHBRED,Receipt,1449814,12,31,2020
4,59203,AARON A. COTUGNO,OWNER RENEWAL,ABLE TO PARTICIPATE,THOROUGHBRED,License,1522183,5,11,2021

 Original dataset: <https://data.ny.gov/Government-Finance/Horse-Racing-Licensing/cz9u-yj7m/data>

## Part 5 - Slide 37

Consider the dataset: `billboard`

> Hint: convert to tidy data **first**

1. Show for each track, how many weeks it spent on the chart

In [56]:
billboard_tidy = billboard.melt(["artist", "track", "date.entered"], var_name="Week", value_name="Rank").dropna(subset=["Rank"])

In [57]:
weeks = billboard_tidy.groupby(["artist", "track"])["Week"].count().reset_index(name="Weeks")
weeks

               artist                    track  Weeks
0               2 Pac  Baby Don't Cry (Keep...      7
1             2Ge+her  The Hardest Part Of ...      3
2        3 Doors Down               Kryptonite     53
3        3 Doors Down                    Loser     20
4            504 Boyz            Wobble Wobble     18
..                ...                      ...    ...
312       Yankee Grey     Another Nine Minutes      8
313  Yearwood, Trisha          Real Live Woman      6
314   Ying Yang Twins  Whistle While You Tw...     14
315     Zombie Nation            Kernkraft 400      2
316   matchbox twenty                     Bent     39

[317 rows x 3 columns]

2. List tracks in decreasing order of number of weeks spent on the chart

In [58]:
weeks.sort_values("Weeks", ascending=False)

               artist                    track  Weeks
62              Creed                   Higher     57
179          Lonestar                   Amazed     55
2        3 Doors Down               Kryptonite     53
121       Hill, Faith                  Breathe     53
63              Creed      With Arms Wide Open     47
..                ...                      ...    ...
315     Zombie Nation            Kernkraft 400      2
96    Estefan, Gloria  No Me Dejes De Quere...      1
105            Fragma           Toca's Miracle      1
107  Ghostface Killah         Cherchez LaGhost      1
196          Master P                  Souljas      1

[317 rows x 3 columns]

3. Show for each track, its top rank

In [59]:
top_rank = billboard_tidy.groupby(["artist", "track"])["Rank"].min().reset_index(name="TopRank")
top_rank

               artist                    track  TopRank
0               2 Pac  Baby Don't Cry (Keep...     72.0
1             2Ge+her  The Hardest Part Of ...     87.0
2        3 Doors Down               Kryptonite      3.0
3        3 Doors Down                    Loser     55.0
4            504 Boyz            Wobble Wobble     17.0
..                ...                      ...      ...
312       Yankee Grey     Another Nine Minutes     74.0
313  Yearwood, Trisha          Real Live Woman     81.0
314   Ying Yang Twins  Whistle While You Tw...     74.0
315     Zombie Nation            Kernkraft 400     99.0
316   matchbox twenty                     Bent      1.0

[317 rows x 3 columns]

4. List tracks in increasing order of its top rank

In [60]:
top_rank.sort_values("TopRank")

              artist                    track  TopRank
316  matchbox twenty                     Bent      1.0
74   Destiny's Child  Independent Women Pa...      1.0
52     Carey, Mariah  Thank God I Found Yo...      1.0
76   Destiny's Child              Say My Name      1.0
63             Creed      With Arms Wide Open      1.0
..               ...                      ...      ...
295          Tuesday                   I Know     98.0
105           Fragma           Toca's Miracle     99.0
267      Smith, Will              Freakin' It     99.0
89    Eastsidaz, The                 Got Beef     99.0
315    Zombie Nation            Kernkraft 400     99.0

[317 rows x 3 columns]

5. Show for each artist, their top rank

In [61]:
artist_top = billboard_tidy.groupby("artist")["Rank"].min().reset_index(name="TopRank")
artist_top

               artist  TopRank
0               2 Pac     72.0
1             2Ge+her     87.0
2        3 Doors Down      3.0
3            504 Boyz     17.0
4                98^0      2.0
..                ...      ...
223       Yankee Grey     74.0
224  Yearwood, Trisha     81.0
225   Ying Yang Twins     74.0
226     Zombie Nation     99.0
227   matchbox twenty      1.0

[228 rows x 2 columns]

6. List artists in increasing order of their top rank

In [64]:
artist_top.sort_values("TopRank")

                  artist  TopRank
6                Aaliyah      1.0
9    Aguilera, Christina      1.0
48                 Creed      1.0
39         Carey, Mariah      1.0
55       Destiny's Child      1.0
..                   ...      ...
119            LL Cool J     98.0
140             Master P     98.0
75                Fragma     99.0
188          Smith, Will     99.0
226        Zombie Nation     99.0

[228 rows x 2 columns]

7. List tracks that only spent one week in the charts

In [63]:
weeks[weeks["Weeks"] == 1]["track"]

96     No Me Dejes De Quere...
105             Toca's Miracle
107           Cherchez LaGhost
196                    Souljas
Name: track, dtype: object

8. List tracks that only spent one week in the charts along with its artist

In [62]:
weeks[weeks["Weeks"] == 1][["track", "artist"]]

                       track            artist
96   No Me Dejes De Quere...   Estefan, Gloria
105           Toca's Miracle            Fragma
107         Cherchez LaGhost  Ghostface Killah
196                  Souljas          Master P