# CPSC 375 Classwork - Data wrangling - Joins and Tidy Data

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ProfAvery/cpsc375-classwork/blob/main/wrangling-tidy.ipynb)

- *Manager*:
- *Recorder*:
- *Presenter*:
- *Timekeeper*:

*Note*: On Google Colab, run the following code cell to download the `cpsc375` module before trying to `import`:

In [1]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [2]:
from cpsc375 import *

## Part 1 - Slide 10

In [3]:
band_members = pd.DataFrame(
    {"Name": ["Mick", "John", "Paul"], "Band": ["Stones", "Beatles", "Beatles"]}
)

band_instruments = pd.DataFrame(
    {"Name": ["John", "Paul", "Keith"], "Plays": ["guitar", "bass", "guitar"]}
)

<table>
<tr>
  <th>
    <code>band_members_4rows</code> (left table)
  </th>
  <th>
    <code>band_instruments_4rows</code> (right table)
  </th>
</tr>
<tr>
  <td>

| Name | Band    |
|------|---------|
| Mick | Stones  |
| John | Beatles |
| Paul | Beatles |
| Paul | Wings   |

  </td>
  <td>

| Name  | Plays  |
|-------|--------|
| John  | guitar |
| Paul  | bass   |
| Keith | guitar |
| Paul  | vocals |

  </td>
</tr>
</table>

Calculate the different joins for these two tables.

First, do them by hand

Then, confirm your results with code

In [15]:
band_members_4rows = pd.concat([
  band_members,
  pd.DataFrame(dict(Name=["Paul"], Band=["Wings"]))
], ignore_index=True)

band_instruments_4rows = pd.concat([
    band_instruments,
    pd.DataFrame(dict(Name=["Paul"], Plays=["vocals"]))
], ignore_index=True)

inner_join_band = band_members_4rows.merge(band_instruments_4rows)
left_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="left")
right_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="right")
outer_join_band = band_members_4rows.merge(band_instruments_4rows, on="Name", how="outer")

inner_join_band, left_join_band, right_join_band, outer_join_band

(   Name     Band   Plays
 0  John  Beatles  guitar
 1  Paul  Beatles    bass
 2  Paul  Beatles  vocals
 3  Paul    Wings    bass
 4  Paul    Wings  vocals,
    Name     Band   Plays
 0  Mick   Stones     NaN
 1  John  Beatles  guitar
 2  Paul  Beatles    bass
 3  Paul  Beatles  vocals
 4  Paul    Wings    bass
 5  Paul    Wings  vocals,
     Name     Band   Plays
 0   John  Beatles  guitar
 1   Paul  Beatles    bass
 2   Paul    Wings    bass
 3  Keith      NaN  guitar
 4   Paul  Beatles  vocals
 5   Paul    Wings  vocals,
     Name     Band   Plays
 0   John  Beatles  guitar
 1  Keith      NaN  guitar
 2   Mick   Stones     NaN
 3   Paul  Beatles    bass
 4   Paul  Beatles  vocals
 5   Paul    Wings    bass
 6   Paul    Wings  vocals)

## Part 2 - Slide 28

Write code to "tidy" this dataset

In [16]:
grades = pd.DataFrame(
  dict(
    CWID=(1234567, 2356902, 5005667),
    NAME=("Mary", "Lee", "Elena"),
    CPSC120=(3, 4, pd.NA),
    CPSC121=(3.3, 3, 2),
    CPSC131=(3, 4, 3.7),
    MATH338=(3, pd.NA, 3.3),
  )
)

In [20]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades")
grades_tidy

       CWID   NAME  Courses Grades
0   1234567   Mary  CPSC120      3
1   2356902    Lee  CPSC120      4
2   5005667  Elena  CPSC120   <NA>
3   1234567   Mary  CPSC121    3.3
4   2356902    Lee  CPSC121    3.0
5   5005667  Elena  CPSC121    2.0
6   1234567   Mary  CPSC131    3.0
7   2356902    Lee  CPSC131    4.0
8   5005667  Elena  CPSC131    3.7
9   1234567   Mary  MATH338      3
10  2356902    Lee  MATH338   <NA>
11  5005667  Elena  MATH338    3.3

In [21]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades").dropna(subset=["Grades"])
grades_tidy

       CWID   NAME  Courses Grades
0   1234567   Mary  CPSC120      3
1   2356902    Lee  CPSC120      4
3   1234567   Mary  CPSC121    3.3
4   2356902    Lee  CPSC121    3.0
5   5005667  Elena  CPSC121    2.0
6   1234567   Mary  CPSC131    3.0
7   2356902    Lee  CPSC131    4.0
8   5005667  Elena  CPSC131    3.7
9   1234567   Mary  MATH338      3
11  5005667  Elena  MATH338    3.3

In [24]:
grades_tidy = grades.melt(["CWID", "NAME"],var_name="Courses",value_name="Grades").dropna(subset=["Grades"]).reset_index(drop=True)
grades_tidy

      CWID   NAME  Courses Grades
0  1234567   Mary  CPSC120      3
1  2356902    Lee  CPSC120      4
2  1234567   Mary  CPSC121    3.3
3  2356902    Lee  CPSC121    3.0
4  5005667  Elena  CPSC121    2.0
5  1234567   Mary  CPSC131    3.0
6  2356902    Lee  CPSC131    4.0
7  5005667  Elena  CPSC131    3.7
8  1234567   Mary  MATH338      3
9  5005667  Elena  MATH338    3.3

## Part 3 - Slide 33

`language_diversity.csv` contains data on the diversity of languages in different countries and other parameters.

In [ ]:
language_diversity = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/language_diversity.csv"
)

Calculate:
 * The total number of languages in every continent

* Add a new variable that shows for every country its population density
  (PopulationDensity=Population/Area)

Hint: **First** convert to tidy data using `pivot()`

Original dataset:
 * <https://github.com/jvcasillas/untidydata#language_diversity>
 * <https://www.researchgate.net/publication/222464328_Explaining_Global_Patterns_of_Language_Diversity>

## Part 4 - Slide 36

`horse_racing.csv` contains data related to horse racing licensing in New York.

In [ ]:
horse_racing = pd.read_csv(
    "https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/datasets/horse_racing.csv"
)

Transform the dataset such that:

* The License column is split into two:
  - `LicenseOrReceipt`: a categorical variable with two categories "License" and "Receipt"
  - `Number`: numeric column with the license/receipt number

* The `Expires` column is split into three:
  - `Year`, `Month`, `Day` (all integers)

 Original dataset: <https://data.ny.gov/Government-Finance/Horse-Racing-Licensing/cz9u-yj7m/data>

## Part 5 - Slide 37

Consider the dataset: `billboard`

> Hint: convert to tidy data **first**

1. Show for each track, how many weeks it spent on the chart

2. List tracks in decreasing order of number of weeks spent on the chart

3. Show for each track, its top rank

4. List tracks in increasing order of its top rank

5. Show for each artist, their top rank

6. List artists in increasing order of their top rank

7. List tracks that only spent one week in the charts

8. List tracks that only spent one week in the charts along with its artist